[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.5

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "K"
mode = "~Alt"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "J"
mode = "~Alt"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002l"
key = "Tab"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "PageUp"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002n"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002@"
key = "Key0"
mods = "Command"

[scrolling]
history = 20000

[selection]
save_to_clipboard = true

[window]
decorations = "full"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 2
y = 2
